application: gdgmalaysia
version: develop
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

# - url: /chapters
#   static_files: templates/chapters.html
#   upload: templates/chapters.html

- url: /.*
  static_files: templates/io15xkl-mdl.html
  upload: templates/io15xkl-mdl.html
